### ISSUE TITLE
Problems in README

### ISSUE THREAD

**Issue by kratos7** [sushilks/mScale#1]
### Running the program

Make sure the use the right .ini file for your setup.

`cp src/main/python/config/example_config.ini ./mscale.ini`

if your current directory has "mscale.ini" then you can omit the ini file form command line

`mscale zmq`

doing mscale zmq  gives this:

Traceback (most recent call last):
  File "/home/abdullah/Envs/env1/bin/mscale", line 20, in <module>
    iFunc = getattr(**import**(dModule, fromlist=[dFunc]), dFunc)
ImportError: No module named zmqtest.runtest

**Comment by kratos7** [comment]
Also
**`pip uninstall -y mScale && pyb install && mscale zqm`**

should be `pip uninstall -y mScale && pyb install && mscale ** zmq`**

RUnning with full command:

**pip uninstall -y mScale && pyb install && mscale zmq`**

Gives this:
`[INFO]  Building binary distribution in /home/abdullah/mScale/target/dist/mScale-0.1.0

## [INFO]  Installing project mScale-0.1.0

## BUILD SUCCESSFUL

Build finished at 2016-03-04 04:06:37
Build took 1 seconds (1247 ms)
Traceback (most recent call last):
  File "/home/abdullah/Envs/env1/bin/mscale", line 19, in <module>
    iFunc = getattr(**import**(dModule, fromlist=[dFunc]), dFunc)
  File "/home/abdullah/Envs/env1/local/lib/python2.7/site-packages/mScale/zmqtest/runtest.py", line 10, in <module>
    from mScale.lib import util
ImportError: No module named lib
`

Because:

`(env1)abdullah@abdullah-test1:~/mScale/src/main/python/mScale⟫ ls
__init__.py  zmqtest
`

There is no "lib" directory. Missing code ?

**Comment by sushilks** [comment]
yes the lib folder was ommited from commit because it was in .gitignore file. 
I have pushed a fix. 
@kratos7 give it another shot.

**Comment by kratos7** [comment]
Next problem.

`(env1)127 abdullah@abdullah-test1:~/mScale⟫ mscale zmq
Traceback (most recent call last):
  File "/home/abdullah/Envs/env1/bin/mscale", line 20, in <module>
    iFunc = getattr(__import__(dModule, fromlist=[dFunc]), dFunc)
ImportError: No module named zmqtest.runtest
`

Fixed by changing
src/main/python/mScale/zmqTest to  **zmqtest**  (wrong folder name)

Next problem after doing  **"mscale zmq"**

`mscale zmq
Running command : /home/abdullah/Envs/env1/bin/mscale zmq
Started a http server to serve content form ./live folder at port 9800
INFO 2016-03-04 07:52:06,366 runtestbase.py:start_init:41 Creating Mesos Client
INFO 2016-03-04 07:52:06,374 runtestbase.py:start_init:43 Creating Marathon Client

```
INFO 2016-03-04 07:52:06,374 runtestbase.py:start_init:45 Delete any pre-existing apps
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/home/abdullah/Envs/env1/local/lib/python2.7/site-packages/mScale/lib/appserver.py", line 38, in run
    os.chdir(self.directory)
OSError: [Errno 2] No such file or directory: 'live'

```

No handlers could be found for logger "marathon"
INFO 2016-03-04 07:52:06,395 runtestbase.py:start_init:48 Waiting for delete to complete
INFO 2016-03-04 07:52:06,401 runtestbase.py:start_init:51 Populating the app on the server
rm: cannot remove ‘../live/zmqScale.tgz’: No such file or directory
tar: target: Cannot stattar (child): live/zmqScale.tgz: Cannot open: No such file or directory
tar: src: Cannot stat: No such file or directory
: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
INFO 2016-03-04 07:52:06,406 runtest.py:**init**:36 Launching the pub app
INFO 2016-03-04 07:52:08,301 mmapi.py:wait_app_ready:82 [1]Waiting for task to move to running stage, current stat staged=0 running=0 expected Running=1
INFO 2016-03-04 07:52:09,313 mmapi.py:wait_app_ready:82 [2]Waiting for task to move to running stage, current stat staged=0 running=0 expected Running=1
INFO 2016-03-04 07:52:10,323 mmapi.py:wait_app_ready:82 [3]Waiting for task to move to running stage, current stat staged=0 running=0 expected Running=1
INFO 2016-03-04 07:52:11,334 mmapi.py:wait_app_ready:82 [4]Waiting for task to move to running stage, current stat staged=0 running=0 expected Running=1
INFO 2016-03-04 07:52:12,344 mmapi.py:wait_app_ready:82 [5]Waiting for task to move to running stage, current stat staged=0 running=0 expected Running=1
INFO 2016-03-04 07:52:13,358 mmapi.py:wait_app_ready:82 [6]Waiting for task to move to running stage, current stat staged=1 running=0 expected Running=1
INFO 2016-03-04 07:52:14,369 mmapi.py:wait_app_ready:82 [7]Waiting for task to move to running stage, current stat staged=0 running=0 expected Running=1
INFO 2016-03-04 07:52:15,379 mmapi.py:wait_app_ready:82 [8]Waiting for task to move to running stage, current stat staged=0 running=0 expected Running=1
INFO 2016-03-04 07:52:16,390 mmapi.py:wait_app_ready:82 [9]Waiting for task to move to running stage, current stat staged=0 running=0 expected Running=1
`

Keeps looping.

**Comment by sushilks** [comment]
Looks like the tar command failed to create a tar file because ./live directory was also missing
I just added it into the repository, @kratos7  checkout again and give it a try.

**Comment by kratos7** [comment]
RUns now

`**No handlers could be found for logger "marathon"
INFO 2016-03-04 08:10:03,168 runtestbase.py:start_init:48 Waiting for delete to complete
INFO 2016-03-04 08:10:03,173 runtestbase.py:start_init:51 Populating the app on the server
rm: cannot remove ‘../live/zmqScale.tgz’: No such file or directory
INFO 2016-03-04 08:10:03,184 runtest.py:__init__:36 Launching the pub app**
INFO 2016-03-04 08:10:04,215 mmapi.py:wait_app_ready:82 [1]Waiting for task to move to running stage, current stat staged=0 running=0 expected Running=1
INFO 2016-03-04 08:10:04,222 runtestbase.py:find_ip_uniqueapp:65 TASK zst-pub.7fc2ba04-e1e0-11e5-9646-42010a0a0002 Running on host : abdullah-test2.c.festive-courier-755.internal IP = 10.10.0.134
INFO 2016-03-04 08:10:05,260 mmapi.py:wait_app_ready:82 [1]Waiting for task to move to running stage, current stat staged=0 running=0 expected Running=1
INFO 2016-03-04 08:10:05,267 runtest.py:__init__:53 Done with launching the pub and sub processes, will scale the sub side now
INFO 2016-03-04 08:10:05,338 runtest.py:__init__:56 Done with starting of scaling the app to 100
INFO 2016-03-04 08:10:05,344 runtest.py:__init__:61 [0] Application count running = 1, staged = 0
INFO 2016-03-04 08:10:06,379 runtest.py:__init__:61 [1] Application count running = 1, staged = 99
INFO 2016-03-04 08:10:07,409 runtest.py:__init__:61 [2] Application count running = 1, staged = 99
INFO 2016-03-04 08:10:08,442 runtest.py:__init__:61 [3] Application count running = 30, staged = 70
INFO 2016-03-04 08:10:09,472 runtest.py:__init__:61 [4] Application count running = 39, staged = 61
INFO 2016-03-04 08:10:10,506 runtest.py:__init__:61 [5] Application count running = 97, staged = 3
INFO 2016-03-04 08:10:11,535 runtest.py:__init__:61 [6] Application count running = 100, staged = 0
INFO 2016-03-04 08:10:11,535 runtest.py:__init__:67 All the tasks are running now. press Ctrl-C to exit. 
INFO 2016-03-04 08:10:11,535 runtest.py:__init__:68   (This app needs to be running to allow scale-up of marathon jobs)
^CINFO 2016-03-04 08:10:37,254 runtestbase.py:wait_for_interrupt:80 Exiting
Calling Server shutdown
Exiting from server
<mScale.zmqtest.runtest.RunTest object at 0x7fc42e78d450>
`

Still throws errors at the start. I could see apps being launched on marathon dashboard.

**Comment by sushilks** [comment]
Looks like it worked, Which error are you talking about ?

"**No handlers could be found for logger "marathon" INFO 2016-03-04 08:10:03,168 "
this one you can ignore, looks like some logging problem.

‘../live/zmqScale.tgz’: No such file or directory INFO 2016-03-04 08:10:03,184 runtest.py:**init**:36 
This one is harmless, I will fix it in the next run.

**Comment by sushilks** [comment]
Ok I have fixed the 2nd error, will close since things are working now.
