### ISSUE TITLE
Link, given on README, for Mesos/Marathon installation has an issue

### ISSUE THREAD

**Issue by tahir24434** [sushilks/mScale#39]
Link, given on README, for Mesos installation has an issue. While trying to install on Ubuntu14.04, error described on this [link](https://github.com/mesosphere/marathon/issues/2357) was hit. 
Solution is to follow below steps before following installation link instructions

sudo add-apt-repository ppa:webupd8team/java
sudo apt-get update
sudo apt-get install oracle-java8-installer
sudo apt-get install oracle-java8-set-default.

A \* note in README might be helpful.

**Comment by scalavision** [comment]
Ok, and if we don't want to use this ppa, is there another option?
