### ISSUE TITLE
mesos_marathon_tests.py integration test failing

### ISSUE THREAD

**Issue by beenum22** [sushilks/mScale#77]
Hi,
I’m trying to deploy hydra but the integration test is failing for me. I’m using ubuntu 14.04 as a base, and mesos and marathon are running on a different machine. I’m following all the steps given in hydra guideline but when I run “pyb publish -x run_unit_tests”, Integration test fails. The logs are given below;

> PyBuilder version 0.11.9
> ## Build started at 2016-08-02 15:44:58
> 
> [INFO]  Building hydra version 0.1.0
> [INFO]  Executing build in /home/hydra/hydra
> [INFO]  Going to execute task publish
> [INFO]  Building distribution in /home/hydra/hydra/target/dist/hydra-0.1.0
> [INFO]  Copying scripts to /home/hydra/hydra/target/dist/hydra-0.1.0/scripts
> [INFO]  Copying resources matching 'LICENSE src/main/data/*' from /home/hydra/hydra to /home/hydra/hydra/target/dist/hydra-0.1.0
> [WARN]  No resources to filter configured. Consider removing plugin.
> [INFO]  Writing setup.py as /home/hydra/hydra/target/dist/hydra-0.1.0/setup.py
> [INFO]  Running integration test mesos_marathon_tests
> ## [ERROR] Integration test failed: /home/hydra/hydra/src/integrationtest/python/mesos_marathon_tests.py
> ## BUILD FAILED - 'exception'
> 
> Build finished at 2016-08-02 15:44:58
> Build took 0 seconds (377 ms)

And I get the following error for mesos_marathon_tests.py;

> Traceback (most recent call last):
>   File "/home/hydra/hydra/src/integrationtest/python/mesos_marathon_tests.py", line 13, in <module>
>     from hydra.lib.hydrabase import HydraBase
>   File "/home/hydra/hydra/target/dist/hydra-0.1.0/hydra/lib/hydrabase.py", line 16, in <module>
>     from hydra.lib.h_analyser import HAnalyser
>   File "/home/hydra/hydra/target/dist/hydra-0.1.0/hydra/lib/h_analyser.py", line 9, in <module>
>     from hydra.lib import util, hdaemon_pb2
> ImportError: cannot import name hdaemon_pb2

Any ideas why is it failing?

**Comment by sushilks** [comment]
It's possible "protoc" compile is not running, you can try to manually run the executable script "make_test_exec.sh" in the home directory, likely it will show something.

**Comment by beenum22** [comment]
It works fine when I use "pyb publish -x run_unit_tests -x run_integration_tests -x verify" instead of "pyb publish -x run_unit_tests"
